config/routes.rb
SampleApp110811::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :items

  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :title, :body, :done
  
  belongs_to :user
  
  default_scope :order => 'items.created_at DESC'
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_many :items, :dependent => :destroy
  
  email_regexp = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  # Automatically create the virtual attribute 'password_confirmation'
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 5..40 }
                       
  validates :name, :presence => true,
                   :length => { :maximum => 50}
  
  validates :email, :presence => true,
                    :format   => { :with => email_regexp},
                    :uniqueness => {:case_sensitive => false}
                       
  before_save :encrypt_password
  
  # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end  
  
  private
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate, :only => [:create, :destroy]
  before_filter :authorized_user, :only => :destroy
  def create
    @item = current_user.items.build(params[:item])
    if @item.save
    flash[:success] = "Item created!"
    redirect_to root_path
    else
    render 'pages/home'
    end
  end

  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  def edit
    @item = Item.find(params[:id])
    @title = "Edit item"
  end

  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    redirect_to user_path(current_user)
  end

  private

  def authorized_user
    @item = Item.find(params[:id])
    redirect_to root_path unless current_user?(@item.user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    @item = Item.new if signed_in?
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
     sign_out
     redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new   # responds to get /users/new by rendering new.html.erb
    @title = "Sign up"
    @user = User.new
  end
  
  def create  # responds to post /users and redirects to /user/i if successful or new.html.erb if not
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to simple.list!"
      redirect_to user_path(@user)
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  def show  # responds to get /user/i by rendering show.html.erb
    @user = User.find(params[:id])
    @items = @user.items.paginate(:page =>params[:page])
    @title = @user.name
  end
  
  def index  # responds to get /users by rendering index.html.erb
    @title = "Current users"
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def logo
    image_tag("logo.png", :alt => "Kays App", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.email
    current_user = user
  end

  def sign_out
    cookies.delete(:remember_token)
    current_user= nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !(current_user.nil?)
  end

  def authenticate
    deny_access unless signed_in?
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page"
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  def clear_return_to
    session[:return_to] = nil
  end
  
  private

  def user_from_remember_token
    userEmail = remember_token
    User.find_by_email(userEmail)
  end

  def remember_token
    cookies[:remember_token] || nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item.html.erb
<tr>
	<td class="items"><span class="title"><%= item.title %></span></td>
	<td class="items"><span class="body"><%= item.body %></span></td>
	<td class="items"><span class="done"><%= item.done %></span></td>
	
	<% if current_user?(item.user) %>
    <td>
    	<%= link_to "edit", edit_item_path(item)%>
    </td>
	<td>
		<%= link_to "delete", item, :method => :delete,
		                            :confirm => "You sure?",
		                            :title => item.title %>
    </td>
    <% end %>  
</tr>

app/views/items/edit.html.erb
<h1>Editing Item</h1>
<%= render 'shared/item_form' %> 

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Done</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.title %></td>
    <td><%= item.body %></td>
    <td><%= item.done %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @item.title %>
</p>

<p>
  <b>Body:</b>
  <%= @item.body %>
</p>

<p>
  <b>Done:</b>
  <%= @item.done %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back to My List', user_path(current_user) %>

app/views/layouts/_header.html.erb
<header>
<div id="inside">
	<div id="banner"><%= link_to logo, root_path %></div>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag    'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag    'styles', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
      <%= render 'layouts/header' %>
      <section class = "round" >
          <div id="inside">
	<div id="main">
      <section class = "round" >
      	<% flash.each do |key, value| %>
      	  <div class="flash <%= key %>"><%= value %></div>
      	<% end %>
		<%= yield %>
	  </section>
	</div>
	
	<div id="sidebar">
		<p>
			<ul>
			<% if signed_in? %>
			<li><%= link_to "My List", current_user %></li>
			<li><%= link_to "Add Item", root_path %></li>
			<li><%= link_to "Sign out", signout_path %></li>
			<% else %>
		    <li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Sign in", signin_path %></li>
			<% end %>
		</p>
	</div>
	
	<div id="footer">By Westley Mojica</div>
</div>

</section>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<% if signed_in? %>
<h1>Add an item to your list</h1>
<%= render 'shared/item_form' %>
<% else %>
<h1>Get started!</h1>
<%= link_to "Sign up now!", new_user_path, :class => "signup_button round" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(object.errors.count, "error") %>
			prohibited this user from being saved:</h2>
		<p>There were problems with the following fields:</p>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_item_form.html.erb
<%= form_for @item do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br />
	<%= f.text_area :body %>
	<br />
	<%= f.label :done %>
	<%= f.check_box :done %>
	<br />
</div>
<div class="actions">
	<%= f.submit "Submit" %>
</div>
<% end %> 

app/views/users/index.html.erb
<h1>Current users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Home', root_path %>

app/views/users/new.html.erb
<h1>simple.list new user creation</h1>
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
<div class="field" >
	<%= f.label :name %>
	<br />
	<%= f.text_field :name %>
</div>
<div class="field" >
	<%= f.label :email %>
	<br />
	<%= f.text_field :email %>
</div>
<div class="field">
	<%= f.label :password %>
	<br />
	<%= f.password_field :password %>
</div>
<div class="field">
	<%= f.label :password_confirmation, "Confirmation" %>
	<br />
	<%= f.password_field :password_confirmation %>
</div>
<div class="actions">
	<%= f.submit "Sign up" %>
</div>
<% end %>

app/views/users/show.html.erb
<h1>Account Information</h1>
<p>
	<strong>Name:</strong> <%= @user.name %>
</p>
<p>
	<strong>Email:</strong> <%= @user.email %>
</p>

<hr />

<h1>My List</h1>
<table class="profile">
	<tr>
		<td class="main"> 
			<% unless @user.items.empty? %>
		<table class="items" summary="User items">
			<tr><td>Item Title</td> 
				<td>Item Description</td>
				<td>Done?</td>
			</tr>
			<%= render @items %>
		</table> 
		<%= will_paginate @items %>
		<% end %> 
		</td>
	</tr>
</table>